version: '3.8'
services:
  mongodb:
    image: mongo:4.4.6
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  wishlist-service:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/wishlistdb

volumes:
  mongodb_data:
